#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input critical Automation/db_user || true
db_go

db_input critical Automation/db_password || true
db_go

db_input critical Automation/email_add || true
db_go

db_input critical Automation/db_name || true
db_go

db_input critical Automation/db_yesno|| true
db_go

db_input critical Automation/account || true
db_go

db_get Automation/db_user
db_user="$RET"

db_get Automation/db_password
db_password="$RET"

db_get Automation/email_add
email_add="$RET"

db_get Automation/db_name
db_name="$RET"

db_get Automation/db_yesno
db_yesno="$RET"

#echo $db_user
#echo $db_password
#echo $email_add
#echo $db_name
#echo $db_yesno

sed -i "1 s/db_user/$db_user/" input
sed -i "2 s/db_password/$db_password/" input
sed -i "3 s/email_add/$email_add/" input
sed -i "4 s/db_name/$db_name/" input
sed -i "5 s/db_yesno/$db_yesno/" input




